version: "3.9"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/media/config/radarr:/config
      - /mnt/media/Films:/movies
      - /mnt/media/Downloads:/downloads
      - /mnt/media/complete:/complete
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - media-net

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/media/config/sonarr:/config
      - /mnt/media/Series:/series
      - /mnt/media/Downloads:/downloads
      - /mnt/media/complete:/complete
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - media-net

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/media/config/lidarr:/config
      - /mnt/media/Muziek:/music
      - /mnt/media/Downloads:/downloads
      - /mnt/media/complete:/complete
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      - media-net

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/media/config/readarr:/config
      - /mnt/media/Boeken:/books
      - /mnt/media/Downloads:/downloads
      - /mnt/media/complete:/complete
    ports:
      - 8787:8787
    restart: unless-stopped
    networks:
      - media-net

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/media/config/bazarr:/config
      - /mnt/media/Series:/series
      - /mnt/media/Films:/movies
      - /mnt/media/complete:/complete
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - media-net

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/media/config/prowlarr:/config
      - /mnt/media/complete:/complete
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - media-net

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/media/config/sabnzbd:/config
      - /mnt/media/Downloads:/downloads
      - /mnt/media/complete:/complete
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - media-net

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/media/config/transmission:/config
      - /mnt/media/Downloads:/downloads
      - /mnt/media/complete:/complete
    ports:
      - 9091:9091
    restart: unless-stopped
    networks:
      - media-net

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/media/config/jellyfin:/config
      - /mnt/media/Films:/movies
      - /mnt/media/Series:/series
      - /mnt/media/Muziek:/music
      - /mnt/media/complete:/complete
    ports:
      - 8096:8096
    restart: unless-stopped
    networks:
      - media-net

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Amsterdam
    ports:
      - 5056:5055
    volumes:
      - /mnt/media/config/jellyseerr:/app/config
    restart: unless-stopped
    networks:
      - media-net

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    user: "1000:1000"
    environment:
      - FB_DATABASE=/database/filebrowser.db
    volumes:
      - /mnt/media:/srv
      - /mnt/media/config/filebrowser:/database
    ports:
      - 8081:80
    restart: unless-stopped
    networks:
      - media-net


  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
    restart: unless-stopped
    networks:
      - media-net

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - 9999:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - media-net
      
networks:
  media-net:
